import type { NextPage } from 'next'
import Head from 'next/head'
import Particles from "react-tsparticles";
import particlesOptions from "../particles.json";
import { ISourceOptions } from "tsparticles";
import Slider from 'react-slick';
// Import css files
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import Header from "../../components/header/Header"
// import Model1 from './Model1';
import ParticleImg from 'components/particle-image/ParticleImg';
import SlideImgItem from 'components/SlideImgItem';
import SkillService from 'components/SkillService';

const Home: NextPage = () => {  
  const slide1_setting = {
    dots: true, arrows: false, infinite: true, speed: 2500, slidesToShow: 5, slidesToScroll: 1, autoplay: true, autoplaySpeed: 10,    
  };
  const slide2_setting = {
    dots: true, arrows: false, infinite: true, speed: 500, slidesToShow: 1, slidesToScroll: 1, autoplay: true, autoplaySpeed: 2000,    
  };
  
  return (
    <div className="next">
      <Head>
        <title>My Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />        
      </Head>
      <main className="glory-main-wraper relative" data-spy="scroll" data-target=".navbar" data-offset="51">

        {/* ----------here-------  */}
        <div id='here'>
          <div className='tsparticle w-full h-[100vh]'>
            <Particles options={particlesOptions as ISourceOptions}/>
          </div>        
          <Header />
          <div className='w-full h-[100vh] absolute left-0 top-[70px] md:top-0 grid grid-cols-1 md:grid-cols-2 z-10' >
            <div className='w-full h-full flex justify-center items-center md:p-16'>              
                <img src="assets/img/text.png"  />              
            </div>
            <div className='flex justify-center h-[40vh] md:h-[100vh]'>
              <div className='md:h-full'>
                <div className='hidden md:block h-[25%] w-full'></div>
                <img src="assets/img/man.png" className='w-auto h-full md:h-[75%] '/>
              </div>
            </div>
          </div>
        </div>

        {/* ----------about-------  */}
        <div id='about' className="glory-about-me md:flex bg-white ">
          <div className='about-me-particle-image w-full md:w-2/6  flex justify-center items-center p-8'>
            <div className=''>
              <ParticleImg/>
            </div>
          </div>
          <div className='about-me-description w-full md:w-4/6 h-full px-4 md:pt-4 pb-4 flex items-center justify-center'>
            <div className='p-4'>
              <div className='text-28 md:text-45 text-black font-bold mb-4'>
                Creative, Passionate and Efficient Developer
              </div>
              <div className='text-base md:text-xl font-bold text-gray-600'>
                Creative, Passionate and Efficient full stack developer with over 9 years of experience in web, mobile and desktop applications design, development and maintenance. Possesses diverse experience of creating multiple highly scalable applications using different tech stacks. Leaded successful transition from LAMP Stack to MEAN Stack to reduce development time and improve system performance. Implemented 3D Scene, Virtual Reality with Three.js and Babylon.js. And have hands-on experience in web hosting & maintenance, Browser Automation and testing, Web Scraping & Crawling. Have worked in all phases of the project life cycle, using a wide variety of tools and frameworks.
              </div>
            </div>
          </div>
        </div>

        {/* ----------resume-------  */}
        <div id='resume' className="glory-resume w-full h-full md:h-[500px] overflow-visible">
            <iframe src="/glory/resume" className='w-full h-[100vh] md:h-[500px] overflow-visible '/>          
        </div>

        {/* ----------portfolio-------  */}
        <div id='portfolio' className="glory-portfolio bg-white flex justify-center items-center px-4 pt-4 pb-8">
          <div className='w-full h-full'>
            <div className='title w-full text-center font-bold text-32 md:text-45 text-gray-700' 
              // style={{color:'#FF6347'}}
            >
              Portfolio
            </div>
            <div className='h-2 md:h-4'></div>
            <div className='w-full hidden md:block'>            
              <Slider {...slide1_setting}>                
                <SlideImgItem imgURL={"assets/img/portfolio/BlueJestic.png"} imgLink={""} skillContent={""} />
                <SlideImgItem imgURL={"assets/img/portfolio/cools.png"} imgLink={""} skillContent={""} />
                <SlideImgItem imgURL={"assets/img/portfolio/campoallecomete.png"} imgLink={""} skillContent={""} />
                <SlideImgItem imgURL={"assets/img/portfolio/exante.png"} imgLink={""} skillContent={""} />
                <SlideImgItem imgURL={"assets/img/portfolio/koenigandreas.png"} imgLink={""} skillContent={""} />
                <SlideImgItem imgURL={"assets/img/portfolio/lonelyplanet.png"} imgLink={""} skillContent={""} />
                <SlideImgItem imgURL={"assets/img/portfolio/ultranote.png"} imgLink={""} skillContent={""} />                
              </Slider>
            </div>
            
            <div className='w-full md:hidden'>            
              <Slider {...slide2_setting}>                
                <SlideImgItem imgURL={"assets/img/portfolio/BlueJestic.png"} imgLink={""} skillContent={""} />
                <SlideImgItem imgURL={"assets/img/portfolio/cools.png"} imgLink={""} skillContent={""} />
                <SlideImgItem imgURL={"assets/img/portfolio/campoallecomete.png"} imgLink={""} skillContent={""} />
                <SlideImgItem imgURL={"assets/img/portfolio/exante.png"} imgLink={""} skillContent={""} />
                <SlideImgItem imgURL={"assets/img/portfolio/koenigandreas.png"} imgLink={""} skillContent={""} />
                <SlideImgItem imgURL={"assets/img/portfolio/lonelyplanet.png"} imgLink={""} skillContent={""} />
                <SlideImgItem imgURL={"assets/img/portfolio/ultranote.png"} imgLink={""} skillContent={""} />                
              </Slider>
            </div>
          </div>
        </div>

        {/* ----------skill-------  */}
        <div id='skill' className="glory-skill ">
          <SkillService/>
        </div>

        {/* ----------contact-------  */}
        <div id='contact' className="glory-contact md:flex bg-black">
          <div className='w-2/6 flex justify-center items-center p-8'>
            <img src='assets/img/contact.png' className='w-full h-full'/>            
          </div>
          <div className='h-full w-4/6 text-white p-16 flex items-center justify-center'>
            <div className=''>
              <div className='text-lg font-semibold mb-4'>
                To Contact Me
              </div>
              <div className='text-base font-normal'>
                Creative, Passionate and Efficient full stack developer with over 9 years of experience in web, mobile and desktop applications design, development and maintenance. Possesses diverse experience of creating multiple highly scalable applications using different tech stacks. Leaded successful transition from LAMP Stack to MEAN Stack to reduce development time and improve system performance. Implemented 3D Scene, Virtual Reality with Three.js and Babylon.js. And have hands-on experience in web hosting & maintenance, Browser Automation and testing, Web Scraping & Crawling. Have worked in all phases of the project life cycle, using a wide variety of tools and frameworks.
              </div>
            </div>
          </div>
        </div>

      </main>
    </div>
  )
}

export default Home
